_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
smtp_on: true
smtp_host: localhost
smtp_hostbackup: ''
smtp_port: '1025'
smtp_protocol: standard
smtp_autotls: true
smtp_timeout: 30
smtp_username: uttamkarmakar400@gmail.com
smtp_password: gdwtwnbsyiqplfel
smtp_from: uttamkarmakar400@gmail.com
smtp_fromname: uttam
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: uttam.karmakar@innoraft.com
smtp_reroute_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
